import { Link } from "@tanstack/react-router";
import { Check, Info, Plus, Play, Star, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useCinemora } from "@/hooks/use-cinemora";
import type { Media } from "@/types/media";

export function MediaCard({media,wide=false}:{media:Media;wide?:boolean}){const {list,toggleList,progress,clearProgress}=useCinemora();const saved=list.includes(media.id);const watched=progress[media.id];const resumable=watched&&watched.pct>0&&watched.pct<95;return <article className={`group relative shrink-0 overflow-hidden rounded-md bg-card ${wide?"w-72":"w-40 sm:w-48 lg:w-52"}`}>
<Link to={media.type==="tv"?"/tv/$slug":"/movie/$slug"} params={{slug:media.slug}} className="block focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">
<div className={wide?"aspect-video":"aspect-[2/3]"}><img src={media.poster} alt="" loading="lazy" width={1536} height={864} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /></div>
<div className="absolute inset-0 bg-gradient-to-t from-background via-transparent to-transparent opacity-80"/><div className="absolute inset-x-0 bottom-0 p-3"><h3 className="truncate font-display text-sm font-semibold text-foreground">{media.title}</h3><p className="mt-1 flex items-center gap-2 text-xs text-muted-foreground"><span className="flex items-center gap-1 text-rating"><Star className="size-3 fill-current"/>{media.rating}</span><span>{media.year}</span><span className="truncate">{media.genres[0]}</span></p>{resumable&&<div className="mt-2"><div className="h-1 w-full overflow-hidden rounded-full bg-muted" role="progressbar" aria-valuenow={watched.pct} aria-valuemin={0} aria-valuemax={100} aria-label={`${media.title} ${watched.pct}% watched`}><div className="h-full bg-primary" style={{width:`${watched.pct}%`}}/></div><p className="mt-1 text-[11px] text-muted-foreground">{watched.pct}% watched</p></div>}</div></Link>
<div className="absolute inset-x-2 bottom-12 hidden translate-y-2 items-center gap-1 opacity-0 transition duration-300 group-hover:translate-y-0 group-hover:opacity-100 sm:flex"><Button size="icon" aria-label={resumable?`Resume ${media.title}`:`Play ${media.title}`} asChild><Link to="/watch/$slug" params={{slug:media.slug}}><Play/></Link></Button><Button size="icon" variant="glass" aria-label={saved?"Remove from My List":"Add to My List"} onClick={()=>toggleList(media.id)}>{saved?<Check/>:<Plus/>}</Button>{resumable&&<Button size="icon" variant="glass" aria-label={`Remove ${media.title} from Continue watching`} onClick={()=>clearProgress(media.id)}><X/></Button>}<Button size="icon" variant="glass" aria-label={`Details for ${media.title}`} asChild><Link to={media.type==="tv"?"/tv/$slug":"/movie/$slug"} params={{slug:media.slug}}><Info/></Link></Button></div>
</article>}
